In [ ]:
## CODE FROM LECTURE

In [31]:
import pandas as pd
import numpy as np

tt = pd.read_csv('https://raw.githubusercontent.com/carlson9/KocPython2020/master/homework/immSurvey.csv')
tt.head()

alphas = tt.stanMeansNewSysPooled
sample = tt.textToSend

from sklearn.feature_extraction.text import CountVectorizer
vec = CountVectorizer()
X = vec.fit_transform(sample)
X

pd.DataFrame(X.toarray(), columns=vec.get_feature_names())

#down-weighting frequent words; term frequency–inverse document frequency (TF–IDF), which weights the word counts by a measure of how often they appear in the documents
from sklearn.feature_extraction.text import TfidfVectorizer
vec = TfidfVectorizer()
X = vec.fit_transform(sample)
pd.DataFrame(X.toarray(), columns=vec.get_feature_names())

from sklearn.model_selection import train_test_split
Xtrain, Xtest, ytrain, ytest = train_test_split(X, alphas,
random_state=1)

from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import ConstantKernel, RBF

rbf = ConstantKernel(1.0) * RBF(length_scale=1.0)
gpr = GaussianProcessRegressor(kernel=rbf, alpha=1e-8)

gpr.fit(Xtrain.toarray(), ytrain)

# Compute posterior predictive mean and covariance
mu_s, cov_s = gpr.predict(Xtest.toarray(), return_cov=True)

#test correlation between test and mus
np.corrcoef(ytest, mu_s)

array([[1.        , 0.68328523],
       [0.68328523, 1.        ]])

In [32]:
## EXTENTION FOR BIGRAMS AND FREQUENCY OF WORD PAIRS

In [34]:
bigram_v = CountVectorizer(ngram_range=(2, 2), token_pattern=r'\b\w+\b', min_df=1)
X = bigram_v.fit_transform(sample)
bigram_v.get_feature_names()


['1 3',
 '1 became',
 '1 boarders',
 '1 difficult',
 '1 immigrants',
 '1 is',
 '1 language',
 '1 not',
 '11 style',
 '12 million',
 '125 and',
 '18 miles',
 '1b my',
 '2 if',
 '2 illegals',
 '2 immigrants',
 '2 process',
 '2 that',
 '2 years',
 '3 high',
 '3 immigrants',
 '3 legals',
 '3 of',
 '3 they',
 '3 women',
 '4 that',
 '4 too',
 '5 immigration',
 '5 of',
 '5 years',
 '600 a',
 '9 11',
 '95 of',
 'a artificially',
 'a better',
 'a bible',
 'a bit',
 'a burden',
 'a catholic',
 'a certain',
 'a chance',
 'a citizen',
 'a comfortable',
 'a complet',
 'a country',
 'a crime',
 'a criminal',
 'a crutial',
 'a daily',
 'a day',
 'a deal',
 'a decent',
 'a degree',
 'a difference',
 'a different',
 'a difficult',
 'a discount',
 'a doctor',
 'a dominant',
 'a double',
 'a drain',
 'a economical',
 'a fence',
 'a fine',
 'a flat',
 'a fortune',
 'a free',
 'a giant',
 'a good',
 'a greater',
 'a green',
 'a heavy',
 'a higher',
 'a hold',
 'a job',
 'a license',
 'a little',
 'a lot',


In [35]:
pd.DataFrame(X.toarray(), columns=bigram_v.get_feature_names())

1 3  1 became  1 boarders  1 difficult  1 immigrants  1 is  1 language  \
0      0         0           0            0             0     0           0   
1      0         0           0            0             0     0           0   
2      0         0           0            0             0     0           0   
3      0         0           0            0             0     0           0   
4      0         0           0            0             0     0           0   
5      0         0           0            0             0     0           0   
6      0         0           0            0             0     0           0   
7      0         0           0            0             0     0           0   
8      0         0           0            0             0     0           0   
9      0         0           0            0             0     0           0   
10     0         0           0            0             0     0           0   
11     0         0           0            0             0     0           0   
12     0         0           0            0             0     0           0   
13     0         0           0            0             0     0           0   
14     0         0           0            0             0     0           0   
15     0         0           0            0             0     0           0   
16     0         0           0            0             0     0           0   
17     0         0           0            0             0     0           0   
18     0         0           0            0             0     0           0   
19     0         0           0            0             0     0           0   
20     0         0           0            0             0     0           0   
21     0         0           0            0             0     0           0   
22     0         0           0            0             0     0           0   
23     0         0           0            0             0     0           0   
24     0         0           0            0             1     0           0   
25     0         0           0            0             0     0           0   
26     0         0           0            0             0     0           0   
27     0         0           0            0             0     0           0   
28     0         0           0            0             0     0           0   
29     0         0           0            0             0     0           0   
..   ...       ...         ...          ...           ...   ...         ...   
310    0         0           0            0             0     0           0   
311    0         0           0            0             0     0           0   
312    0         0           0            0             0     0           0   
313    0         0           0            0             0     0           0   
314    0         0           0            1             0     0           0   
315    0         0           0            0             0     0           0   
316    0         0           0            0             0     0           0   
317    0         0           0            0             0     0           0   
318    0         0           0            0             0     0           0   
319    0         0           0            0             0     0           0   
320    0         0           0            0             0     0           0   
321    0         0           0            0             0     0           0   
322    0         0           0            0             0     0           0   
323    0         0           0            0             0     0           0   
324    0         0           0            0             0     0           0   
325    0         0           0            0             0     0           0   
326    0         0           0            0             0     0           0   
327    0         0           0            0             0     0           0   
328    0         0           0            0            

In [64]:
X_train, X_test, y_train, y_test = train_test_split(X, alphas, test_size=0.5, random_state=42)

In [74]:
rbf = ConstantKernel(1.0) * RBF(length_scale=1.0)
gpr = GaussianProcessRegressor(kernel=rbf, alpha=1e-8)
gpr.fit(X_train.toarray(), y_train)
mu, cov = gpr.predict(X_test.toarray(), return_cov=True)
print(mu, cov)
np.corrcoef(y_test, mu_s)

C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\gaussian_process\gpr.py:469: ConvergenceWarning: fmin_l_bfgs_b terminated abnormally with the  state: {'grad': array([-8.15571858,  1.16056753]), 'task': b'ABNORMAL_TERMINATION_IN_LNSRCH', 'funcalls': 50, 'nit': 2, 'warnflag': 2}
  ConvergenceWarning)


[-1.43716168e-05 -1.52971976e-04 -5.44241445e-10 -3.07856342e-39
 -2.96188781e-02 -6.19485777e-01 -1.57351194e-01 -2.15142107e-08
 -4.15543035e-38 -1.34681157e-08 -5.76879439e-03 -2.16946906e-07
 -6.59747236e-05 -2.24654304e-11 -2.79430753e-02 -6.19485777e-01
 -6.73303166e-09 -4.65537295e-17 -1.56789978e+00 -2.99182097e-08
 -2.45481464e-06 -1.27991032e-04 -2.26976723e-05 -9.67865922e-02
 -9.85568136e-01 -8.76265815e-01 -1.53152090e-01 -2.39963061e-02
 -6.19485777e-01 -3.54250842e-06 -6.17061366e-09 -3.50835952e-05
 -1.84915887e-02 -3.89936334e-03 -2.40174489e-02 -3.89392729e-01
 -5.70248891e-07 -1.65253523e-04 -2.54889437e-12 -2.44763205e-01
 -4.65307134e-03 -7.55534790e-22 -9.48263130e-04 -4.03670580e-01
 -1.02381287e-01 -1.43892494e-04 -5.30347573e-03 -1.47516747e-01
 -1.04171084e-10 -6.07871640e-02 -9.15349210e-02 -8.72984010e-06
 -1.49795939e-04 -1.18426549e-07 -8.12249219e-06 -7.62224594e-16
 -9.50332212e-03 -1.69416839e-28 -2.36388551e-03 -1.53851191e-01
 -9.48942023e-03 -5.70755

array([[1.        , 0.38457984],
       [0.38457984, 1.        ]])

In [76]:
X_train2, X_test2, y_train2, y_test2 = train_test_split(
X, alphas, random_state=42)


In [77]:
gpr.fit(X_train2.toarray(), ytrain)
mu, cov = gpr.predict(X_test2.toarray(), return_cov=True)
np.corrcoef(y_test2, mu)

C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\gaussian_process\gpr.py:469: ConvergenceWarning: fmin_l_bfgs_b terminated abnormally with the  state: {'grad': array([-5.26458653, -0.95032412]), 'task': b'ABNORMAL_TERMINATION_IN_LNSRCH', 'funcalls': 48, 'nit': 3, 'warnflag': 2}
  ConvergenceWarning)


array([[1.        , 0.17352737],
       [0.17352737, 1.        ]])

In [ ]:
#CORRELATION FELL WITH THE DEFAULT TRAINING SET OF 75/25 